title: Swords under the Sun | Playtest materials

theme: minima
skin: dark

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

header_pages:
  - toc.md
  - heroes/
